/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectInvoice.com;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import static java.nio.file.Files.lines;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import projectInvoice.model.InvoiceMain;
import static java.nio.file.Files.lines;
import java.text.ParseException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import projectInvoice.model.InvoiceDetail;
import projectInvoice.model.InvoiceMaintableModel;
import projectInvoice.model.InvoicedetailtableModel;
import javax.swing.JFrame;
import javax.swing.JDialog;
import javax.swing.JTextField;

/**
 *
 * @author SG5530150
 */
 public class invoicefram extends JFrame implements ActionListener,ListSelectionListener {

    /**
     * Creates new form invoicefram
     */
    public invoicefram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        CustomernameLable = new javax.swing.JLabel();
        DCustomername = new javax.swing.JTextField();
        InvoiceDteLable = new javax.swing.JLabel();
        DInvoiceDate = new javax.swing.JTextField();
        Invoicenumber = new javax.swing.JLabel();
        InvNO = new javax.swing.JLabel();
        jBoknewInv = new javax.swing.JButton();
        jBoknewInv.addActionListener(this);
        jBcancelnewInv = new javax.swing.JButton();
        jBcancelnewInv.addActionListener(this);
        jDialog2 = new javax.swing.JDialog();
        Itemname = new javax.swing.JLabel();
        jTFitemname = new javax.swing.JTextField();
        jLitemprice = new javax.swing.JLabel();
        jTFitemPrice = new javax.swing.JTextField();
        jLItemcount = new javax.swing.JLabel();
        jTFItemCount = new javax.swing.JTextField();
        jBOKItems = new javax.swing.JButton();
        jBOKItems.addActionListener(this);
        jBcancelitem = new javax.swing.JButton();
        jBcancelitem.addActionListener(this);
        jScrollPane1 = new javax.swing.JScrollPane();
        MainTable = new javax.swing.JTable();
        MainTable.getSelectionModel().addListSelectionListener(this);
        createInvoice = new javax.swing.JButton();
        createInvoice.addActionListener(this);
        Deleteinvoicebutton = new javax.swing.JButton();
        Deleteinvoicebutton.addActionListener(this);
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTInvoiceItem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        saveinvoicebutton = new javax.swing.JButton();
        saveinvoicebutton.addActionListener(this);
        DeleteItema = new javax.swing.JButton();
        DeleteItema.addActionListener(this);
        Invoivedatetextfield = new javax.swing.JTextField();
        cusomernametextfield = new javax.swing.JTextField();
        invnumberlabel = new javax.swing.JLabel();
        totalInvoice = new javax.swing.JLabel();
        jLInvoicenumber = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadMenuItem = new javax.swing.JMenuItem();
        loadMenuItem.addActionListener(this);
        saveMunuItem = new javax.swing.JMenuItem();
        saveMunuItem.addActionListener(this);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        CustomernameLable.setText("Cusromer Name");

        DCustomername.setColumns(30);

        InvoiceDteLable.setText("Invoice Date");

        DInvoiceDate.setMaximumSize(new java.awt.Dimension(6, 20));

        Invoicenumber.setText("Invoice NO.");

        jBoknewInv.setText("OK");
        jBoknewInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoknewInvActionPerformed(evt);
            }
        });

        jBcancelnewInv.setText("Cancel");
        jBcancelnewInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelnewInvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addComponent(InvoiceDteLable)
                                .addGap(37, 37, 37)
                                .addComponent(DInvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addComponent(CustomernameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DCustomername, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addComponent(Invoicenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(InvNO))))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jBoknewInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(83, 83, 83)
                        .addComponent(jBcancelnewInv)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Invoicenumber)
                    .addComponent(InvNO))
                .addGap(20, 20, 20)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomernameLable)
                    .addComponent(DCustomername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InvoiceDteLable)
                    .addComponent(DInvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoknewInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBcancelnewInv))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        Itemname.setText("Item Name");

        jLitemprice.setText("Item Price");

        jLItemcount.setText("Item Count");

        jBOKItems.setText("Add Item");
        jBOKItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOKItemsActionPerformed(evt);
            }
        });

        jBcancelitem.setText("cancel Item");

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLItemcount, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(Itemname)
                            .addComponent(jLitemprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFitemname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFItemCount, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFitemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jBOKItems)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBcancelitem)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFitemname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Itemname))
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLitemprice))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTFitemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLItemcount)
                    .addComponent(jTFItemCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBOKItems)
                    .addComponent(jBcancelitem))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(MainTable);

        createInvoice.setText("Create new Invoice");
        createInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createInvoiceActionPerformed(evt);
            }
        });

        Deleteinvoicebutton.setText("Delete Invoice");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTInvoiceItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTInvoiceItem);

        jLabel1.setText("Invoice item");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jLabel2.setText("Invoice number");

        jLabel3.setText("Invoive Date");

        jLabel4.setText("Customer Name");

        jLabel5.setText("total");

        saveinvoicebutton.setText("Create new Item");
        saveinvoicebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveinvoicebuttonActionPerformed(evt);
            }
        });

        DeleteItema.setText("Delete Item");
        DeleteItema.setToolTipText("");
        DeleteItema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteItemaActionPerformed(evt);
            }
        });

        totalInvoice.setText("jLabel7");

        jMenu1.setText("File");

        loadMenuItem.setText("load");
        loadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(loadMenuItem);

        saveMunuItem.setText("save");
        saveMunuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMunuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveMunuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(createInvoice)
                        .addGap(42, 42, 42)
                        .addComponent(Deleteinvoicebutton)
                        .addGap(116, 116, 116)
                        .addComponent(saveinvoicebutton)
                        .addGap(69, 69, 69)
                        .addComponent(DeleteItema))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLInvoicenumber)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(invnumberlabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Invoivedatetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(totalInvoice))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cusomernametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(invnumberlabel)
                            .addComponent(jLInvoicenumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Invoivedatetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cusomernametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(totalInvoice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createInvoice)
                            .addComponent(Deleteinvoicebutton)
                            .addComponent(saveinvoicebutton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DeleteItema)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveinvoicebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveinvoicebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveinvoicebuttonActionPerformed

    private void DeleteItemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteItemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteItemaActionPerformed

    private void loadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadMenuItemActionPerformed

    private void saveMunuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMunuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMunuItemActionPerformed

    private void createInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createInvoiceActionPerformed

    private void jBcancelnewInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelnewInvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBcancelnewInvActionPerformed

    private void jBoknewInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoknewInvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoknewInvActionPerformed

    private void jBOKItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOKItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBOKItemsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
  

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new invoicefram().setVisible(true);
                     //   jDialog1.setVisible(false);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomernameLable;
    private javax.swing.JTextField DCustomername;
    private javax.swing.JTextField DInvoiceDate;
    private javax.swing.JButton DeleteItema;
    private javax.swing.JButton Deleteinvoicebutton;
    private javax.swing.JLabel InvNO;
    private javax.swing.JLabel InvoiceDteLable;
    private javax.swing.JLabel Invoicenumber;
    private javax.swing.JTextField Invoivedatetextfield;
    private javax.swing.JLabel Itemname;
    private javax.swing.JTable MainTable;
    private javax.swing.JButton createInvoice;
    private javax.swing.JTextField cusomernametextfield;
    private javax.swing.JLabel invnumberlabel;
    private javax.swing.JButton jBOKItems;
    private javax.swing.JButton jBcancelitem;
    private javax.swing.JButton jBcancelnewInv;
    private javax.swing.JButton jBoknewInv;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLInvoicenumber;
    private javax.swing.JLabel jLItemcount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLitemprice;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFItemCount;
    private javax.swing.JTextField jTFitemPrice;
    private javax.swing.JTextField jTFitemname;
    private javax.swing.JTable jTInvoiceItem;
    private javax.swing.JMenuItem loadMenuItem;
    private javax.swing.JMenuItem saveMunuItem;
    private javax.swing.JButton saveinvoicebutton;
    private javax.swing.JLabel totalInvoice;
    // End of variables declaration//GEN-END:variables
private DateFormat date1=new SimpleDateFormat("dd-MM-yyyy");
private InvoiceMaintableModel InvoiceMaintableshow;
private List<InvoiceMain> ListOfMains=new ArrayList<>();
private List<InvoiceDetail> itemsofmain=new ArrayList<>();
private InvoicedetailtableModel Invoicedetailtableshow;
String filePath = "E:\\main.txt";
//String filePath = "E:\\main.csv";
         File file = new File(filePath);
         String filePath1 = "E:\\items.txt";
         File file1 = new File(filePath1);


//private DCustomername=new JTextField(30);
    @Override
    public void actionPerformed(ActionEvent e) {
        switch(e.getActionCommand())
        {
            case("load"):
                    loadfile();
                break;
            case("Create new Invoice"):
                   createNewInvoicedialog();
                 break;
            case("OK"):
                    addnewinvoice();
                  break;
            case("Cancel"):
                  closeinvoiceDailog();
                  break;
                  case("Create new Item"):
                  createNewItemDialog();
                  break;
                 case("Add Item"):
                     AddItemToInvoice();
                     break;
                     case( "Delete Item"):
                         DeleteItem();
                         break;
                         case("Delete Invoice"):
                                 DeleteInvoice();
                                 break;
                                case("save") :
                                 save();
                                 break;
                  
        }
     //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private  void loadfile()
    {   
         try {
            BufferedReader Mainbr = new BufferedReader(new FileReader(file));
            String row=null;
            // loop to read from file to invoice Main
            while((row=Mainbr.readLine())!=null)
            {
                String[] MainInvParts=row.split(",");
                String Invnumstr=MainInvParts[0];
                String Invdatestr=MainInvParts[1];
                String Invcustomername=MainInvParts[2];
                int Invnumer=Integer.parseInt(Invnumstr);
                Date invdate=date1.parse(Invdatestr);
           //  System.out.println("Date is     :"+invdate);
               InvoiceMain inv=new InvoiceMain(Invnumer,Invcustomername,invdate); 
               ListOfMains.add(inv);
            } 
            System.out.println("Afterloop size of mains    "+ListOfMains.size());
            //loops for Invoice detail
            BufferedReader Detailbr = new BufferedReader(new FileReader(file1));
            String rowdetail=null;
            while((rowdetail=Detailbr.readLine())!=null)
            {
           String[] detailpatrs=rowdetail.split(",");
           String invnumbstr=detailpatrs[0];
           String itemname=detailpatrs[1];
           String itempricestr=detailpatrs[2];
           String itemcountstr=detailpatrs[3];
           int invmain= Integer.parseInt(invnumbstr);
           double itemprice= Double.parseDouble(itempricestr); 
           int itemcount= Integer.parseInt(itemcountstr);
           System.out.println("invmain"+invmain+"itemprice"+itemprice+"itemcount"+itemcount);
           InvoiceMain main=findmaininvoive(invmain);
           System.out.println("the maiiiiiiiiiiiiin"+main.getInvnumber());
           InvoiceDetail itemsofmain=new InvoiceDetail(itemname,itemprice,itemcount,main);
           main.getLines().add(itemsofmain);
          }
          InvoiceMaintableshow=new InvoiceMaintableModel(ListOfMains);
          MainTable.setModel(InvoiceMaintableshow);
          MainTable.validate();
         }
         catch (Exception ex) {
             ex.printStackTrace();        }
         System.out.print("okkkkkkkkkkkkkkkkkkkkkkkkk");
           }
      
    
      private void save()  {
         try{
              int selectedrowindex=MainTable.getSelectedRow();
             FileWriter main=new FileWriter(file,true);
        BufferedWriter mainbr = new BufferedWriter(main);
        InvoiceMain selectedRow;
        selectedRow = InvoiceMaintableshow.getListOfMains().get(selectedrowindex);
         String invnumb=(""+selectedRow.getInvnumber());
         String  invdate=(""+selectedRow.getInvdate());
        String name=selectedRow.getCustomername();
     //   mainbr.newLine();
        mainbr.write(""+invnumb+","+invdate+","+name);
        mainbr.close();
        ////////////////////////////////////////
        int selectitem=selectedrowindex=jTInvoiceItem.getSelectedRow();
        FileWriter item=new FileWriter(file1,true);
        BufferedWriter itemsbr = new BufferedWriter(item);
        InvoiceDetail itemsrow;
        itemsrow  =Invoicedetailtableshow.getItems().get(selectitem);
        String itemname=(""+itemsrow.getItemname());
       String count=(""+itemsrow.getItemcount());
       String price=(""+itemsrow.getItemprice());
     //  itemsbr.newLine();
        itemsbr.write(""+invnumb+","+itemname+","+price+","+count);
        System.out.print(""+invnumb+","+itemname+","+price+","+count);
        itemsbr.flush();
        itemsbr.close();
            }
          catch(Exception ex){}
       /* String mains="";
        String items="";
        try
        {
        for(InvoiceMain main:ListOfMains){
           // BufferedReader Mainbr = new BufferedReader(new FileReader(file));
       //     String row=null;
            // loop to read from file to invoice Main
           /* while((row=Mainbr.readLine())!=null)
            {
                String[] MainInvParts=row.split(",");
                String Invnumstr=MainInvParts[0];
            }
            mains+=main.getdatatosave();
            mains+='\n';
            for(InvoiceDetail item : main.getLines())
            {
               items+=item.getdatatosave();
               items+='\n';
            
              
            FileWriter main1=new FileWriter(file,true);
        BufferedWriter mainbr = new BufferedWriter(main1);
        mainbr.write(mains);
       mainbr.flush();
       mainbr.close();
       FileWriter item1=new FileWriter(file1,true);
        BufferedWriter itembr = new BufferedWriter(item1);
        itembr.write(items);
       itembr.flush();
       itembr.close();
            }
        }
        }
      
               catch(Exception ex){}*/
       
        
        }
        
    
      private InvoiceMain findmaininvoive(int invnumber)
         {
             InvoiceMain main=null;
              for(InvoiceMain inv:ListOfMains) 
              {
                  if(invnumber==inv.getInvnumber())
                  {
                      main=inv;
                      break;
                  }
              }
                      return main ;
            
         }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        System.out.println("select out");
       // selectedrow();
       int selectedrowindex=MainTable.getSelectedRow();
        if(selectedrowindex>=0)
        {
            InvoiceMain selectedRow;
            selectedRow = InvoiceMaintableshow.getListOfMains().get(selectedrowindex);
            totalInvoice.setText(""+selectedRow.getInvtotal());
            jLInvoicenumber.setText(""+selectedRow.getInvnumber());
            cusomernametextfield.setText(selectedRow.getCustomername());
            Invoivedatetextfield.setText(""+selectedRow.getInvdate());
    
            ArrayList<InvoiceDetail> items=selectedRow.getLines();
            Invoicedetailtableshow=new InvoicedetailtableModel(items);
          jTInvoiceItem.setModel(Invoicedetailtableshow);
          jTInvoiceItem.validate();
  
        }
    }
    
    private void selectedrow()
    {
        
    }

  
    private void createNewInvoicedialog()
    {
        int v=maxinvnumber();
        jDialog1.setVisible(true);
        jDialog1.setLocation(50, 50);
       jDialog1.setSize(500, 500);
       jDialog1.setLayout(new GridLayout(4,2)); 
       jDialog1.add(Invoicenumber);
       jDialog1.add(InvNO);
       jDialog1.add(CustomernameLable);
       jDialog1.add(DCustomername);
       jDialog1.add(InvoiceDteLable);
       jDialog1.add(DInvoiceDate);
       jDialog1.add(jBoknewInv);
       jDialog1.add(jBcancelnewInv);
       InvNO.setText(""+v);
       jDialog1.pack();
    }
     private void createNewItemDialog()
    {
       jDialog2.setVisible(true);
       jDialog2.setLocation(50, 50);
       jDialog2.setSize(500, 500);
       jDialog2.setLayout(new GridLayout(4,2)); 
       jDialog2.add(Itemname);
       jDialog2.add(jTFitemname);
       jDialog2.add(jLitemprice);
       jDialog2.add(jTFitemPrice);
       jDialog2.add(jLItemcount);
       jDialog2.add(jTFItemCount);
       jDialog2.add(jBOKItems);
       jDialog2.add(jBcancelitem);
       jDialog2.pack();
    }

    private void addnewinvoice() {
        String customername=DCustomername.getText();
        String InvoiceDatestr=DInvoiceDate.getText();
        int maxinvnum=maxinvnumber();
        try{
            Date newinvoicedate=date1.parse(InvoiceDatestr);
            InvoiceMain main=new InvoiceMain(maxinvnum,customername,newinvoicedate);
            ListOfMains.add(main);
            InvoiceMaintableshow.fireTableDataChanged();
            jDialog1.setVisible(false);
         
        }
        
        catch(ParseException ex) {
             ex.printStackTrace();
                                }
    }             

  public int maxinvnumber()
    {
        int y=0;
    try{
        BufferedReader Mainbr = new BufferedReader(new FileReader(file));
            String row=null;
            
            // loop to read from file to invoice Main
            while((row=Mainbr.readLine())!=null)
            {
                String[] MainInvParts=row.split(",");
                String Invnumstr=MainInvParts[0];
                int x=Integer.parseInt(Invnumstr);
                if (y<x)
                {y=x;}
            }
    }catch(Exception ex){}
    return y+1;
      
    }
            

    private void closeinvoiceDailog() 
    {
    jDialog1.setVisible(false);
    jDialog1.dispose();
    }

    private void AddItemToInvoice() {
         //Item from Jdalog
         String Itemname=jTFitemname.getText();
         String Itempricestr=jTFitemPrice.getText();
         String  Itemcountstr =jTFItemCount.getText();
         int  Itemcount=Integer.parseInt(Itemcountstr);
         double Itemprice=Double.parseDouble(Itempricestr);
         jDialog2.setVisible(false);
        int selectedrowindex=MainTable.getSelectedRow();
             InvoiceMain main=InvoiceMaintableshow.getListOfMains().get(selectedrowindex);
             String show=main.toString();
             System.out.println(show);
      InvoiceDetail items= new InvoiceDetail(Itemname,Itemprice,Itemcount,main) ;
      main.addiveline(items);
      totalInvoice.setText(""+main.getInvtotal());
           Invoicedetailtableshow.fireTableDataChanged();
           InvoiceMaintableshow.fireTableDataChanged();
    }

    private void DeleteItem() {
        int ItemIndex=jTInvoiceItem.getSelectedRow();
        InvoiceDetail items=Invoicedetailtableshow.getItems().get(ItemIndex);
        Invoicedetailtableshow.getItems().remove(ItemIndex);
         Invoicedetailtableshow.fireTableDataChanged();
           InvoiceMaintableshow.fireTableDataChanged();
           totalInvoice.setText(""+items.getHeader().getInvtotal());
    }

    private void DeleteInvoice() {
        int ivoiceindex=MainTable.getSelectedRow();
        InvoiceMain main=InvoiceMaintableshow.getListOfMains().get(ivoiceindex);
        InvoiceMaintableshow.getListOfMains().remove(ivoiceindex);
         InvoiceMaintableshow.fireTableDataChanged();
        //delete items
        Invoicedetailtableshow = new InvoicedetailtableModel( new ArrayList<InvoiceDetail>());
        //Invoicedetailtableshow.getItems().remove(main.getLines().);
        totalInvoice.setText("");
        cusomernametextfield.setText("");
        Invoivedatetextfield.setText("");
        jLInvoicenumber.setText("");
       // Invoicedetailtableshow.getItems().remove(main.getLines());
        jTInvoiceItem.setModel(Invoicedetailtableshow);
        Invoicedetailtableshow.fireTableDataChanged();
        

    }
}
